name: Scheduled Git repo monitor
on:
  schedule:
    - cron:  "0 0 * * *"
jobs:
  build:
    name: Compare tags
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Compare tags
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          set -xe
          python check_for_new_versions.py